import type { Trip, Group, Member } from '@/types'

export const MOCK_TRIPS: Trip[] = [
  {
    id: 't1',
    from: 'Nanyuki',
    to: 'Nairobi',
    price: 1200,
    departureAt: '2026-05-17T07:00:00',
    when: 'Sun · 7:00 AM',
    seatsLeft: 3,
    seatsTotal: 4,
    tripType: 'SELF DRIVE',
    full: false,
    isPublic: true,
    status: 'OPEN',
    driver: {
      id: 'd1',
      name: 'Aisha Wanjiku',
      initials: 'AW',
      avatarColor: 'blue',
      verified: true,
      rating: 4.9,
      tripCount: 42,
      bio: 'Weekly Nanyuki commuter. Reliable, on-time, comfortable Toyota Premio.',
    },
    notes: 'Pickup at Nanyuki Mall. Two stops in Nairobi: CBD and Westlands.',
  },
  {
    id: 't2',
    from: 'Nairobi',
    to: 'Nanyuki',
    price: 1100,
    departureAt: '2026-05-18T06:30:00',
    when: 'Mon · 6:30 AM',
    seatsLeft: 0,
    seatsTotal: 4,
    tripType: 'HIRED DRIVER',
    full: true,
    isPublic: true,
    status: 'FULL',
    driver: {
      id: 'd2',
      name: 'Peter Mwangi',
      initials: 'PM',
      avatarColor: 'orange',
      verified: false,
      rating: 4.2,
      tripCount: 18,
    },
    notes: '',
  },
  {
    id: 't3',
    from: 'Nanyuki',
    to: 'Nairobi',
    price: 1500,
    departureAt: '2026-05-17T11:00:00',
    when: 'Sun · 11:00 AM',
    seatsLeft: 2,
    seatsTotal: 4,
    tripType: 'TAXI',
    full: false,
    isPublic: true,
    status: 'OPEN',
    driver: {
      id: 'd3',
      name: 'Joshua Kamau',
      initials: 'JK',
      avatarColor: 'green',
      verified: true,
      rating: 4.7,
      tripCount: 87,
    },
    notes: 'Door-to-door taxi rental. Pickup anywhere in Nanyuki.',
  },
]

export const MOCK_GROUPS: Group[] = [
  {
    id: 'g1',
    name: 'Nanyuki Neighbours',
    emoji: '🏔',
    color: '#7697F5',
    members: 47,
    lastActive: '12m',
    lastTrip: 'Aisha · Nanyuki → Nairobi · Sun 7AM',
  },
  {
    id: 'g2',
    name: 'Mt Kenya Cycling Club',
    emoji: '🚴',
    color: '#EF9B5B',
    members: 23,
    lastActive: '2h',
    lastTrip: 'Joshua · Saturday morning ride pickup',
  },
  {
    id: 'g3',
    name: 'Tatu City Commuters',
    emoji: '🏙',
    color: '#4FBA88',
    members: 112,
    lastActive: 'yesterday',
    lastTrip: 'No trips this week',
  },
]

export const MOCK_MEMBERS: Member[] = [
  { id: 'm1', name: 'Aisha Wanjiku', initials: 'AW', role: 'Admin · founder',         avatarColor: 'blue',   verified: true },
  { id: 'm2', name: 'Peter Mwangi',  initials: 'PM', role: 'Member · 12 trips',        avatarColor: 'orange' },
  { id: 'm3', name: 'Joshua Kamau',  initials: 'JK', role: 'Member · 4 trips',         avatarColor: 'green',  verified: true },
  { id: 'm4', name: 'Susan Njeri',   initials: 'SN', role: 'Member · joined last week', avatarColor: 'ink' },
]
